- name: installing nginx
  hosts: web
  become: yes
  tasks:
  - name: nginx installing
    ansible.builtin.package:
      name: nginx
      state: present
  - name: nginx starting
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 