- name: play1
  hosts: multi
  connection: local
  tasks:
  - name: play1 is initiated
    ansible.builtin.debug:
      msg: "This is play1"

- name: play2
  hosts: local
  connection: local
  tasks:
  - name: play2 is initiated
    ansible.builtin.debug:
      msg: "This is play2"