- name: tasklevel
  hosts: local
  connection: local
  vars:
    employee: saikiran
    employer: "Accenture ind private limited"
    emp_id: 13272805
  tasks:
  - name: tasklevel variables
    vars:
      employer: "Infosys"
    ansible.builtin.debug:
      msg: "Iam {{ employee }}, working in {{ employer }}, and emplyee_id is {{ emp_id }}"

  - name: playlevel
    ansible.builtin.debug:
     msg: "Iam {{ employee }}, working in {{ employer }}, and emplyee_id is {{ emp_id }}"